title: Nate Roberts Tech
description: Blog where I write about my projects, studies, and anything else tech related I find interesting

url: https://nathanroberts55.github.io/long-haul/
baseurl: ''
paginate_path: 'blog/page:num/'
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-postcss
paginate: 5

postcss:
  cache: false

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: nathanroberts55
  linkedin: naterobertstech

google_analytics:

disqus:
  shortname: naterobertstech
